name: flutter_generic_widgets
description: Flutter generic widgets which is easy to use and can be used frequently.
version: 0.0.1
homepage: https://github.com/arfuhad/flutter_generic_widgets
repository: https://github.com/arfuhad/flutter_generic_widgets.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  datetime_picker_formfield: ^1.0.0
  equatable: ^2.0.0
  intl: ^0.16.1
  meta: ^1.2.4
  radio_button_form_field: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter: null
